---
title: "Getting & Clearing Data Class Project CodeBook"
date: "Wednesday, February 11, 2015"
output: html_document
---

##Purpose
The purpose of this project is to cleanse and merge data taken from the accelerometer and gyroscope sensors on a Samsung Galaxy S II smartphone worn by thirty volunteers performaing a series of tasks (Walking, Walking Upstairs, Walking Downstairs, Sitting, Standing, and Laying).  Datasets of this measurement data have been taken in two stages, a train stage and a test stage.  This project merges the data and extracts the test data for the mean and standard deviation for each measurement.  Details regarding the experiment, measurement methods, and data pre-processing steps can be found at 
**http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones**

##Raw Data Source
The raw data used for this project was downloaded from **https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip**, on February 02, 2015, 10:41:45 AM.

## Input Data Files
On downloading the data contained in the zip file, the following eight (8) text files were extracted and used to process the data:

* activity_labels.txt - contains the codes used to identify the six activities examined during the experimental trials.  These codes were used to assign meaningful names to variables by converting the numeric code into a trial task name (Walking, Walking Upstairs, Walking Downstairs, Sitting, Standing, and Laying).

* features.txt - contains a list of the 561 individual test measurements made during each trial. These features were used to label the columns of interest in this analysis

* subject_train.txt - contains a list of the train subjects associated with each trial conducted during the training phase.  This data was used to assign a subject field indicating which of six subjects performed the train trial associated with each record in the X_train.txt file.  

* X_train.txt - contains the data measurements taken during each of the trials conducted during the training phase.  The 561 columns of this data were named using the contents of the features.txt file.  

* y_train.txt - contains the order in which the train activities were performed. Using this data an activity name was assigned to each row of the X_train.txt data. 

* subject_test.txt - contains a list of the test subjects associated with each trial conducted during the testing phase. This data was used to assign a subject field indicating which of six subjects performed the test trial associated with each record in the X_test.txt file

* X_test.txt - contains the data measurements taken during each of the trials conducted during the testing phase.

* y_test.txt - contains the order in which the activities were performed using the codes defined by in activity_labels.txt file. 


##Processing Steps
In cleansing and preparing data for analysis, the process outlined in the following steps was employed:  

###Creating Clean Test and Train Data Frames  
In Cleaning the data sets:  
1. The eight data files were read into the R environment and assigned names as follows:  
  
Item | Input File | R Data Record 
-----|------------|--------------------  
a. | activity.txt  | act_tab  
b. | features.txt  | feat_tab     
c. | subject_train.txt | sub_train 
d. | X_train.txt | data_train  
e. | y_train.txt | acts_train  
f. | subject_test.txt | sub_test  
g. | X_test.txt | data_test  
h. | y_test.txt | acts_test

2. The columns of data_train and data_test were labeled using the contents of feat_tab after it is appropriately modified to update values to remove naming duplication.  
3. A train_df was formed by combining the sub_train, acts_train, and data_train tables.  
4. The train_df was mutated to add a new column entitled Stage containing the word "Train."  
5. A test_df was formed by combining the sub_test, acts_test, and data_test tables.    
6. The test_df was mutated to add a new column entitled Stage containing the word "Test."  
  
### Merging The Data Frames and Extracting the Mean & STD Measurements  
The Test and Train data_frames were separately processed to create two data frames(trn_data, and test_data) which resulted from extracting important  mean and standard deviation data.  The data selected included the 8 measurments listed in the following table.  These measurements were selected because they were computed from the data collected during the original experiments and form the most comprehensive summary.  
  
Item | Variable                   | Description 
-----|----------------------------|----------------------
1. | fBodyAccMag-mean             | Mean of Full Body Accel Magnitude 
2. | fBodyBodyAccJerkMag-mean()   | Mean of Full Body Accel Jerk      
3. | fBodyBodyGyroMag-mean() | Mean of Full Body Gyros Movement         
4. | fBodyBodyGyroJerkMag-mean() | Mean of Full Body Gyro Jerk     
5. | fBodyAccMag-std()  | Std Dev of Full Body Acceleration
6. | fBodyBodyAccJerkMag-std() | Std Dev of Full Body Accel Jerk  
7. | fBodyBodyGyroMag-std()  | Std Dev of Full Body Gyro Movement
8. | fBodyBodyGyroJerkMag-std()  | Std Dev of Full Body Gyro jerk

The process followed to create these summary data frames included the following steps:  
1.  Extracting columns containing the phrases "fbody", "Mag()", or "std()".   
2.  The Test and Train data frames were then formed by combining the results of step 1 with the sub and act dataframes created during the earlier creation and cleansing steps.  
  

### A TIDY data set was created
The resulting combined data frame was then processed to generate a Tidy data set containing the mean data for each activity by subject


### run_analysis.R Script
The steps required to perform this transformation are provided in a separate R Program script entitled run_analysis.R.  Before executing this script, please refer to the ReadMe file, shich describes the necessary structure of the working directory for proper execution.
The script is included below: 
  
  
```{r eval=FALSE}
require("dplyr")
require("reshape2")

#  Define the loading environment
home_dir <- getwd()
upper_dir <- "UCI_HAR_Dataset"
train_dir <- "train"
test_dir <- "test"

# Test for proper woking environment
if (!file.exists(paste(home_dir, upper_dir, sep="/")) |
         !file.exists(paste(upper_dir, train_dir, sep= "/")) |
         !file.exists(paste(upper_dir, test_dir, sep ="/"))) {
     print("Error Incorrect working environment")
}  else {
# Working environment is good


     # .... Useful Utility Functions ........

     adj_names <- function(val, tgt, col) {
          #  Reads a table/data.frame column specified by col and
          #  greps for the tgt phrase.  If the Tgt is found add the current row number to
          #  the contents of the cell
          for (idx in 1:nrow(val)) {
               k <- length(grep(tgt, val[idx,col]))
               if (k > 0) {
                    val[idx, 2] <- paste(as.character(idx),
                                         as.character(val[idx,2]), sep="-")
               }
          }
          val
     }


     # Load label files
     activity_file <- "activity_Labels.txt"
     features_file <- "features.txt"
     act_tab <- read.table(paste(home_dir, upper_dir, activity_file, sep="/"), sep=" ")
     feat_tab <- read.table(paste(home_dir, upper_dir, features_file, sep="/"), stringsAsFactors= FALSE, sep=" ")

     # Make Duplicate Column labels Unique by adding the row number to the label
     feat_tab <- adj_names(feat_tab, "bandsEnergy", 2)

     # Load training data files
     print ("Loading and cleaning train data files")
     subject_train_file <- "subject_train.txt"
     train_data_file <- "X_train.txt"
     train_acts_file <- "y_train.txt"
     sub_train <- as_data_frame(read.table(paste(home_dir, upper_dir, train_dir,
                             subject_train_file, sep="/"), sep=""))
     acts_train <- as_data_frame(read.table(paste(home_dir, upper_dir,
                             train_dir, train_acts_file, sep="/"), sep=""))
     train_df <- as_data_frame(read.table(paste(home_dir, upper_dir, train_dir,
                              train_data_file, sep="/"),  stringsAsFactors= FALSE, sep=""))

     colnames(train_df) <- feat_tab[,2]
     colnames(sub_train) <- "Subject"
     acts_train <- data.frame(apply(acts_train, 1, function(elm){elm <-act_tab[elm,2]}))
     colnames(acts_train) <- "Activity"

     # Load test data files
     print ("Loading and cleaning test data files")
     subject_test_file <- "subject_test.txt"
     test_data_file <- "X_test.txt"
     test_acts_file <-"y_test.txt"
     sub_test <- as_data_frame(read.table(paste(home_dir, upper_dir,
                              test_dir, subject_test_file, sep="/"), sep=""))
     acts_test <- as_data_frame(read.table(paste(home_dir, upper_dir,
                              test_dir, test_acts_file, sep="/"), sep=""))
     test_df <- as_data_frame(read.table(paste(home_dir, upper_dir, test_dir,
                              test_data_file, sep="/"),  stringsAsFactors= FALSE, sep=""))
     colnames(test_df) <- feat_tab[,2]
     colnames(sub_test) <- "Subject"
     acts_test <- data.frame(apply(acts_test, 1, function(elm){elm <-act_tab[elm,2]}))
     colnames(acts_test) <- "Activity"

     ## Now Extract the mean and Std columns from test_df and train_df
     print ("Extracting Mean and Std Columns and merging data files")
     tstmn_df <- test_df %>%
          select(contains("fbody")) %>%
          select(contains("Mag")) %>%
          select(contains("Mean()"))
     tststd_df <- test_df %>%
          select(contains("fbody")) %>%
          select(contains("Mag")) %>%
          select(contains("std()"))

     tst_data <- cbind(sub_test, acts_test, tstmn_df, tststd_df)
     tst_data <- arrange(tst_data, Subject, Activity)
     colnames(tst_data) <- gsub("BodyBody","Body", colnames(tst_data))

     trnmn_df <- train_df %>%
          select(contains("fbody")) %>%
          select(contains("Mag")) %>%
          select(contains("Mean()"))
     trnstd_df <- train_df %>%
          select(contains("fbody")) %>%
          select(contains("Mag")) %>%
          select(contains("std()"))

     trn_data <- cbind(sub_train, acts_train, trnmn_df, trnstd_df)
     trn_data <- arrange(trn_data, Subject, Activity)
     colnames(trn_data) <- gsub("BodyBody","Body", colnames(trn_data))

     # Creating the Training Tidy dataset
     print("Creating and outputting the Training Tidy dataset")
     trn_tidy <- melt(trn_data, id=c("Subject", "Activity"), measure.vars= colnames(trn_data[3:5]))
     tst_tidy <- melt(tst_data, id=c("Subject", "Activity"), measure.vars= colnames(tst_data[3:5]))
     write.table(tst_tidy, "Tidy_data.txt", row.names=FALSE)


}


```  

##License:
This dataset comes from experiments described in:

*Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. __Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine.__ International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012*

This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.
